# Generated by Django 3.2.8 on 2022-04-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_todo'),
    ]

    operations = [
        migrations.CreateModel(
            name='upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('pdffile', models.FileField(default=None, max_length=250, null=True, upload_to='assign/')),
            ],
        ),
    ]
