# Generated by Django 3.2.8 on 2022-04-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_upload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='upload',
        ),
        migrations.AddField(
            model_name='homework',
            name='pdffile',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='assign/'),
        ),
    ]
