# Generated by Django 3.2.8 on 2022-04-19 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20220419_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='pdffile',
        ),
    ]
