# Generated by Django 3.2.8 on 2022-04-17 10:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0003_auto_20220417_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='due',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
