# Generated by Django 3.2.8 on 2022-04-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0004_alter_assignment_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='subject',
            field=models.CharField(default='', max_length=50),
        ),
    ]
