# Generated by Django 3.2.8 on 2022-04-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0005_alter_assignment_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='marks',
            field=models.IntegerField(default=0),
        ),
    ]
